### ISSUE TITLE
Domain Analysis

### ISSUE THREAD

**Issue by umireon** [dosen/dosen#1]
Please do the domain analysis.
You can draw a class diagram by hand or with PC.
The artifacts will be supposed to be uploaded here.
Due to 10.25(Sat).
You will be appreciated very much if you have done this task by third meeting.

Cheers! :baseball:

**Comment by penguin215** [comment]
ちょっと遅れる

**Comment by umireon** [comment]
PUNT to Sprint-4 :football:

**Comment by penguin215** [comment]
![default](https://cloud.githubusercontent.com/assets/9244301/4782311/48f523f2-5ceb-11e4-8bed-9b30889bb94b.jpg)

**Comment by umireon** [comment]
:+1:

**Comment by umireon** [comment]
@startuml
プレイヤー <|-- ユーザー
プレイヤー <|-- コンピュータ

プレイヤー "1"..>"1" 動物 : 作成する

動物 "1"-->"1" 動物 : 攻撃する

class 動物 {
  -名前 : String
  -HP : number
  -AT : number
  -DEF : number
  -体長 : number
  -体重 : number
  -ページ長 : number
  -検索数 : number

  -getHP(体長, 体重, ページ長, 検索数) : number
  -getAT(体長, 体重, ページ長, 検索数) : number
  -getDEF(体長, 体重, ページ長, 検索数) : number
}
@enduml

**Comment by umireon** [comment]
![domain](https://cloud.githubusercontent.com/assets/1067855/4782372/90369388-5cee-11e4-9dc4-a8d0d6b2b78e.png)

**Comment by umireon** [comment]
Converted the diagram into plantuml.

**Comment by umireon** [comment]
動物 --> Wikipedia
動物 --> GoogleSearch
class Wikipedia {
  -名前 : String
  -体長 : number
  -体重 : number
  -ページ長 : number
}
class GoogleSearch {
  -キーワード : String
  -検索数 : number
}
:question:

**Comment by umireon** [comment]
Getter and setter methods are not necessary at the domain analysis,
since fields imply them.

**Comment by penguin215** [comment]
へえ，そうなんだ

**Comment by umireon** [comment]
at least, in my opinion, getter and setter methods are matters of program design, not of domain modeling.

**Comment by umireon** [comment]
We are going to improve this domain analysis, since the domain analysis is the MOST important part of this projrct, of cource :mortar_board:

**Comment by umireon** [comment]
Sorry, at 10.29 meeting

**Comment by umireon** [comment]
ALMOST DONE in meeting. We are going to create a precise version. Thanks for wonderful jobs :100:
