### ISSUE TITLE
戦闘時メトリックの考案

### ISSUE THREAD

**Issue by ff7RtBW** [dosen/dosen#20]
11/7 9:00 まで

**Comment by umireon** [comment]
@ff7RtBW can u implement metrics in javascript?

**Comment by ff7RtBW** [comment]
すみません
メトリックをjavascriptで実行（？） というのがよく分かりません…

**Comment by umireon** [comment]
extractor.jsをいじれば，どんなメトリックも実装できるはず．

**Comment by ff7RtBW** [comment]
bodyLength とかbodyWeightと同じようなかんじでいろいろ追加していくということでいいでしょうか？

**Comment by umireon** [comment]
とりあえずbodyLengthの評価関数を書き換えたら，なにかしら動くと思います．

**Comment by ff7RtBW** [comment]
extractor.js にある le-2 や le-3 はどういう意味ですか？

**Comment by umireon** [comment]
new metrics
