### ISSUE TITLE
Build Prototype

### ISSUE THREAD

**Issue by umireon** [dosen/dosen#4]
:smiley:

**Comment by umireon** [comment]
Our Prototype is: https://github.com/dosen/dosen/blob/prototype/prototype.html
Please clone dosen/dosen and Checkout remote branch prototype, then open prototype.html.
See what happen and review here.

**Comment by ff7RtBW** [comment]
プロトタイプの作成ありがとうございます。
それぞれの動物の各ステータスが数字として見られるのは良いと思いました。
ステータスの値にあわせて、自分のゲージがたまる、または相手のゲージが減る等するとより面白くなりそうだと思います。

**Comment by mash1209** [comment]
プログラムの作成ありがとうございます。ステータスが数字で視覚的にわかることがユーザーにも扱いやすく良いと感じました。

**Comment by umireon** [comment]
We have to create the layout prototype.
